 {
      "@context": "http://schema.org",
      "@type": "VideoGame",
      "name": "Battle Realms: Zen Edition",
      "url": "http://battlerealms.com",
      "image": "https://i.imgur.com/Fanupyc.png",
      "description": "Battle Realms is a fantasy real-time strategy game inspired by the stories told in Martial Arts movies and oriental mythology. Develop your tiny peasant village into a highly trained and deadly efficient clan of warriors who are ready to die with your name on their lips.",
      "inLanguage":["English"],
      },
      "author":{
        "@type":"Organization",
        "name":"Ed Del Castillo",
    },
      "publisher":"Ed Del Castillo",
      "genre":["Real-Time Strategy","3D","Action"],
      "processorRequirements":"3.2Hz",
      "memoryRequirements":"1024 MB",
      "storageRequirements":"1024 MB",
      "gamePlatform":["PC game"],
}
